title: <p align="center">Gopi Krishna </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gopi-krishna-l-a4b412133">LinkedIn</a> |
  <a href="https://github.com/sgk259">GitHub</a>
  
  <br>   
  I'm working on Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
